### ISSUE TITLE
SentryError: Native Client is not available, can't start on native

### ISSUE THREAD

**Issue by outaTiME** [expo/sentry-expo#120]
Hi guys, 
today i update to sentry-expo 2.1 and im getting the following error "SentryError: Native Client is not available, can't start on native." any advice ? rolling back to 2.0.4 not fix the issue, some update from sentry ?

![IMAGE 2020-06-05 13:15:30](https://user-images.githubusercontent.com/140472/83899316-a19d5b80-a72e-11ea-801d-4910359704da.jpg)

Thanks !!!

**Comment by outaTiME** [comment]
Related with https://github.com/expo/sentry-expo/issues/112

**Comment by cruzach** [comment]
I think this is likely due to a change in `@sentry/react-native@1.4.3` that was just released 12 hours ago

using `@sentry/react-native@1.4.2`, I don't have this issue

**Comment by cruzach** [comment]
just published sentry-expo v2.1.2 which comes with that version pinned ^

not that you'll need to remove node_modules and yarn.lock and then reinstall

**Comment by alexbchr** [comment]
@cruzach Just to make sure, I just updated to latest `sentry-expo` version. I don't have this error, but the same message shows up in my Expo Logs when logging a crash:

```
Sentry Logger [Log]: Failed to get device context from native: SentryError: Native Client is not available, can't start on native.
```

**Comment by luizjr** [comment]
> @cruzach Just to make sure, I just updated to latest `sentry-expo` version. I don't have this error, but the same message shows up in my Expo Logs when logging a crash:
> 
> ```
> Sentry Logger [Log]: Failed to get device context from native: SentryError: Native Client is not available, can't start on native.
> ```

I'm having exactly the same problem, the error still appears in the LOG and no errors are actually reported in the sentry panel.

**Comment by instanceof-inf** [comment]
Hey guys.. any news on this? I am having the same issue as @alexbchr

**Comment by cruzach** [comment]
I'm still not able to reproduce this on a blank project after `yarn add sentry-expo`. If someone can provide a repo that reproduces this issue (you can leave out your DSN and project info, of course) I'll be happy to look into it

**Comment by nottmey** [comment]
We fixed this by changing our our `yarn.lock`. We pinned it back to `"@sentry/react-native@1.3.9":` and it worked again.

**Comment by cruzach** [comment]
https://github.com/expo/sentry-expo/issues/112#issuecomment-639859268

**Comment by janKir** [comment]
I face the same issue (no error but the message in the logs -  errors dont appear in Sentry) with `sentry-expo@2.1.2` and `@sentry/react-native@1.4.3`. Removing node_modules, yarn.lock clearing the cache does not help. 

I also tried to pin `sentry-expo@2.1.1` and thus be able to use the latest version of `@sentry/react-native@1.6.3`. This still doesn't work but the behavior slightly changed: On app start, there is a warning `Sentry Logger [Warn]: Note: Native Sentry SDK is disabled.` and when the ErrorBoundary tries to call Sentry: `Sentry Logger [Log]: Failed to get device context from native: SentryError: Native is disabled`.

**Comment by teckel12** [comment]
@janKir Try running `expo start -c` to clear the Metro bundler cache, this worked for me.

**Comment by teckel12** [comment]
It appears it's not throwing the error anymore.  But, if there's actually an error in some other part of your code, Sentry isn't working and logs the message to the console:

> Sentry Logger [Log]: Failed to get device context from native: SentryError: Native Client is not available, can't start on native.

I've tried using all the different versions listed above (clearing node_modules and package-lock.json between) with the same results.  I can't get Sentry to work at all anymore with Expo 38.0.2.  This issue shouldn't be closed.

**Comment by cruzach** [comment]
the device context error is an upstream sentry issue, it's not checking whether or not the `enableNative` option is set before calling `new DeviceContext` - https://github.com/getsentry/sentry-react-native/blob/f01f0abf6560a5439d9fb8301a4cb13ffbdf78d2/src/js/sdk.ts#L70

I'll submit a PR for this, and I believe the `enableNative` option isn't being considered elsewhere so I'll try to root that out

@teckel12 if no errors are being reported in your case, that's a different issue. Despite these logs, `sentry-expo` itself is still working for me so can you provide a repro?

**Comment by teckel12** [comment]
@cruzach You are correct.  It is logging the Sentry errors, just displaying the console message.

> Sentry Logger [Log]: Failed to get device context from native: SentryError: Native Client is not available, can't start on native.

**Comment by giautm** [comment]
Hi @cruzach , I noticed is `@sentry/react-native` was publish version 1.7.1 includes a fix for this issue. So, can I upgrade `@sentry/react-native` to that version? (I using Expo SDKv38).

**Comment by cruzach** [comment]
Yeah @giautm feel free to try the release candidate version, installable with `yarn add sentry-expo@next`, which includes that version bump 😄 Lmk if you have issues

**Comment by PaulKish** [comment]
This is still reoccurring unfortunately. Could you bump up the @sentry/react-native version? This issue seems to have been fixed with v.1.4.5

**Comment by jakemitchellxyz** [comment]
Happening for me as well; need that bump ideally

**Comment by Elijen** [comment]
Using `sentry-expo@3.0.0-rc3` with `@sentry/react-native@1.7.1` on Expo v38 and still getting the error. Any workarounds?

**Comment by cruzach** [comment]
yep this is my mistake, corrected here- https://github.com/getsentry/sentry-react-native/pull/1084 

You can use [patch-package](https://www.npmjs.com/package/patch-package) to apply that change without waiting for the PR to land, though

**Comment by janbiasi** [comment]
Somehow I still experience the same issue by using `sentry-expo` in version `3.0.3` (uses `@sentry/react-native` version `1.9.0`) but only if I publish it to expo and try to run it on my iOS device, it works completely fine if I start the local expo server in production mode and use the same iOS device:

```
Unhandled JS Exception: s: Native Client is not available, can't start on native.
```

Any advice like downgrading to a certain version?

**Comment by Fr4gger** [comment]
> Somehow I still experience the same issue by using `sentry-expo` in version `3.0.3` (uses `@sentry/react-native` version `1.9.0`) but only if I publish it to expo and try to run it on my iOS device, it works completely fine if I start the local expo server in production mode and use the same iOS device:
> 
> ```
> Unhandled JS Exception: s: Native Client is not available, can't start on native.
> ```
> 
> Any advice like downgrading to a certain version?

Experiencing the same. Any help is appreciated.

**Comment by cruzach** [comment]
@Fr4gger and @janbiasi please open a new issue with a minimal reproducible demo

**Comment by DanLeCornu** [comment]
> > Somehow I still experience the same issue by using `sentry-expo` in version `3.0.3` (uses `@sentry/react-native` version `1.9.0`) but only if I publish it to expo and try to run it on my iOS device, it works completely fine if I start the local expo server in production mode and use the same iOS device:
> > ```
> > Unhandled JS Exception: s: Native Client is not available, can't start on native.
> > ```
> > 
> > 
> > Any advice like downgrading to a certain version?
> 
> Experiencing the same. Any help is appreciated.

FYI Am getting the same run time error in an ejected app when running yarn android - "Native Client is not available, can't start on native."

using "sentry-expo": "^3.0.3",

will post a reproducible demo when I find the time

**Comment by cruzach** [comment]
> in an ejected app

@DanLeCornu please make sure you've followed the additional instructions for bare apps- https://docs.expo.io/guides/using-sentry/#additional-bare-workflow-setup

**Comment by pawel3ala** [comment]
and here we go again on 
`"sentry-expo": "^3.0.4",`
anyone else experiencing this issue lately?

**Comment by kttien** [comment]
I'm experiencing this issue on `"sentry-expo": "^3.0.4"` as well when loading the app through Expo Go. Was recently experimenting with ejecting to the bare workflow, and I'm not sure if that somehow broke a bunch of stuff, but the source code has remained the same.

**Comment by Zakrevskijj** [comment]
Same issue here "sentry-expo": "^3.0.4"

**Comment by cruzach** [comment]
Locking this issue to prevent more people from just saying "same issue"

if you're experiencing this problem, please open a new bug report with a reproducible demo so that we can fix it 😄
